MODEL:
  CHANNELS: [16, 32, 64, 128, 256]
  NUM_RES_UNITS: 2
  STRIDES: [2, 2, 2, 2]

LOSS:
  USE_LOSS: 'DiceBettiMatching'     # Avilable options 'Dice', 'ClDice', 'Dice_ClDice', 'DiceBettiMatching', 'DiceWasserstein'
  SKEL_METHOD: 'DMT'                # Avilable options 'DMT', 'Shit', 'Menten', 'Viti' 
  ALPHA: 0.01

TRAIN:
  NUM_WORKERS: 0                   # Number of data loading threads
  SEED: 10                          # random seed for reproducibility
  MAX_EPOCHS: 2500
  LR: 0.001
  BATCH_SIZE: 48                     # Batch size for a single GPU
  VAL_BATCH_SIZE: 1
  SAVE_PATH: "./models/"            # save path for the checkpoint
  LOG_PATH: "./runs/"               # save path for the tensorboard log
  VAL_INTERVAL: 100                 # validation interval
  LOG_INTERVAL: 10                  # tensorboard log interval