DATA:
  DIM: 3                                                        # data dimension
  DATA_PATH: '/home/home/supro/projects/DMT-images/data/synthetic/'                                # Path to dataset
  FORMAT: '.nii.gz'
  DATASET: 'synthetic'                                          # Dataset name
  IMG_SIZE: [32, 32, 32]                                        # Input image size
  TRAIN_SAMPLES: 1
  VAL_SAMPLES: 1
  NUM_PATCH: 8                                                  # no of patch from each volume
  IN_CHANNELS: 1
  OUT_CHANNELS: 1