MODEL:
  CHANNELS: [64,128,256,512,1024]
  NUM_RES_UNITS: 2
  STRIDES: [2, 2, 2, 2]

LOSS:
  USE_LOSS: 'Dice_ClDice'     # Avilable options 'Dice', 'ClDice', 'Dice_ClDice'
  SKEL_METHOD: 'Shit'                # Avilable options 'DMT', 'Shit', 'Menten', 'Viti' 
  ALPHA: 0.5

TRAIN:
  NUM_WORKERS: 16                   # Number of data loading threads
  SEED: 10                          # random seed for reproducibility
  MAX_EPOCHS: 300
  LR: 0.001
  BATCH_SIZE: 4                     # Batch size for a single GPU
  SAVE_PATH: "./models/"            # save path for the checkpoint
  LOG_PATH: "./runs/"               # save path for the tensorboard log
  VAL_INTERVAL: 10                  # validation interval
  LOG_INTERVAL: 1                   # tensorboard log interval