DATA:
  DIM: 3                                                        # data dimension
  DATA_PATH: '/home/home/supro/projects/DMT-images/data/topcow/'                                # Path to dataset
  KEY: 'mr_roi'
  FORMAT: '.nii.gz'
  DATASET: 'topcow_mr'                                          # Dataset name
  IMG_SIZE: [64, 64, 32]                                        # Input image size
  PIXDIM: [0.20, 0.20, 0.20]
  TRAIN_SAMPLES: 72
  VAL_SAMPLES: 18
  NUM_PATCH: 2                                                  # no of patch from each volume
  IN_CHANNELS: 1
  OUT_CHANNELS: 1